### ISSUE TITLE
Feature Request: Implementation in R or Python?

### ISSUE THREAD

**Issue by kravarik** [PCAubin/GRISLI#1]
Is the a future plan to implement GRISLI in an open-source language such as R or Python? The majority of single-cell sequencing code development is on these platforms and many scientists do not have access to Matlab.

**Comment by PCAubin** [comment]
Hello! No such plan unfortunately as GRISLI is related to TIGRESS (http://projets.cbio.mines-paristech.fr/~ahaury/svn/dream5/html/index.html) which is coded in Matlab as well. SPAMS exists in other languages. GRISLI could probably run on Octave for a free legal program that could run the .m files.
